name: CI-Workflow

on:
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: forgejo
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run make lint
        run: make lint

      - name: Run make test
        run: make test

      - name: Run make build
        run: make build

      - name: Run make trivy
        run: make trivy
